/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.mycompany.gtp.Cuenta;
import com.mycompany.gtp.manejaCuenta;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seba Garcia
 */
public class ListaCuentas extends javax.swing.JFrame {

    private manejaCuenta mc;
    private int id_usu;
    /**
     * Creates new form ListaCuentas
     */
    public ListaCuentas(int id) {
        initComponents();
        id_usu = id;
        mc = new manejaCuenta();
        dibujaTab();
        muestraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelGTP = new javax.swing.JLabel();
        labelLC = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Cuentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(700, 450));
        setSize(new java.awt.Dimension(700, 450));

        labelGTP.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labelGTP.setText("GuardaTuPassword");

        labelLC.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labelLC.setText("Listar Cuentas");

        btnAtras.setText("Volver a Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jTable_Cuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Cuentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(118, 118, 118)
                                    .addComponent(labelGTP, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(163, 163, 163)
                                    .addComponent(labelLC))))
                        .addGap(0, 164, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelGTP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLC)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel modeloTab = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int fil, int col)
        {
            return false;
        }
    };
    
    private void dibujaTab()
    {
        jTable_Cuentas.setModel(modeloTab);
        String[] columnasTabla = {"Usuario","Contraseña","Descripción"};
        modeloTab.setColumnIdentifiers(columnasTabla);
        
        // Para no permitir el redimensionamiento de las columnas con el ratón
        jTable_Cuentas.getTableHeader().setResizingAllowed(false);
        
        // Así se fija el ancho de las columnas
        jTable_Cuentas.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable_Cuentas.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable_Cuentas.getColumnModel().getColumn(2).setPreferredWidth(140);
    }
    
    private void rellenarTablaColabora(List<Cuenta> lc)
    {
        Object[] columna = new Object[3];

        while(!lc.isEmpty())
        {
            Cuenta c = lc.get(0);
            columna[0] = c.getUsuario();
            columna[1] = c.getClave();
            columna[2] = c.getDescripcion();
            modeloTab.addRow(columna);
            lc.remove(c);
        }
    }
    
    private void muestraTabla()
    {
        List<Cuenta> lc = mc.getCuentas();
        rellenarTablaColabora(lc);
    }
    
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Cuentas;
    private javax.swing.JLabel labelGTP;
    private javax.swing.JLabel labelLC;
    // End of variables declaration//GEN-END:variables
}
