/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.mycompany.gtp.session;

/**
 *
 * @author Seba Garcia
 */
public class VentanaUsuarioLogueado extends javax.swing.JFrame {

    private session s;
    private int id_usu;
    /**
     * Creates new form VentanaUsuarioLogueado
     */
    public VentanaUsuarioLogueado(int id, session sesion) {
        initComponents();
        s = sesion;
        id_usu = id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelGTP = new javax.swing.JLabel();
        labelUL = new javax.swing.JLabel();
        btnGestUsu = new javax.swing.JButton();
        btnAddCuenta = new javax.swing.JButton();
        btnVerCuentas = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(700, 450));
        setSize(new java.awt.Dimension(700, 450));

        labelGTP.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labelGTP.setText("GuardaTuPassword");

        labelUL.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labelUL.setText("Usuario Logueado");

        btnGestUsu.setText("Gestión de Usuario");
        btnGestUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestUsuActionPerformed(evt);
            }
        });

        btnAddCuenta.setText("Añadir Cuenta");
        btnAddCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCuentaActionPerformed(evt);
            }
        });

        btnVerCuentas.setText("Ver Mis Cuentas");
        btnVerCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuentasActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelUL))
                                    .addComponent(labelGTP)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGestUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVerCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGTP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUL)
                .addGap(83, 83, 83)
                .addComponent(btnGestUsu)
                .addGap(18, 18, 18)
                .addComponent(btnAddCuenta)
                .addGap(18, 18, 18)
                .addComponent(btnVerCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestUsuActionPerformed
        GestionUsuario gu = new GestionUsuario(id_usu);
        gu.setVisible(true);
    }//GEN-LAST:event_btnGestUsuActionPerformed

    private void btnAddCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCuentaActionPerformed
        AddCuenta ac = new AddCuenta(id_usu);
        ac.setVisible(true);
    }//GEN-LAST:event_btnAddCuentaActionPerformed

    private void btnVerCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuentasActionPerformed
        ListaCuentas lc = new ListaCuentas(id_usu);
        lc.setVisible(true);
    }//GEN-LAST:event_btnVerCuentasActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        s.cerrarSesion();
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCuenta;
    private javax.swing.JButton btnGestUsu;
    private javax.swing.JButton btnVerCuentas;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel labelGTP;
    private javax.swing.JLabel labelUL;
    // End of variables declaration//GEN-END:variables
}
