package com.mycompany.gtp;
// Generated 22-may-2019 13:21:22 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable 
{
    private int id;
    private String usuario;
    private String clave;

    public Usuario() 
    {
    }

    public Usuario(int id, String usuario, String clave) 
    {
       this.id = id;
       this.usuario = usuario;
       this.clave = clave;
    }
   
    public int getId() 
    {
        return this.id;
    }
    
    public void setId(int id) 
    {
        this.id = id;
    }
    
    public String getUsuario() 
    {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) 
    {
        this.usuario = usuario;
    }
    public String getClave() 
    {
        return this.clave;
    }
    
    public void setClave(String clave) 
    {
        this.clave = clave;
    }
}


